### ISSUE TITLE
Add Gebruikers

### ISSUE THREAD

**Issue by JurreSerrarens** [JurreSerrarens/C-CovadisDing#5]
## Voeg gebruikers toe die kunnen inloggen

Gebruikers moeten beschikken over:
Naam
Email
Wachtwoord(Hashed/encrypted)
Telefoonnummer

**Comment by samromer** [comment]
![aClown](https://github.com/JurreSerrarens/C-CovadisDing/assets/131258016/ab9103bc-f96e-4a85-afb4-60bf014d05e4)

**Comment by JurreSerrarens** [comment]
# Thank you for your feedback would you consider using C-CovadisDing in the future?
Please tell us what you liked about our program so we can improve it in the future.














***B A L L S***

**Comment by samromer** [comment]
![Elden-ring-dung-eater-cinematic](https://github.com/JurreSerrarens/C-CovadisDing/assets/131258016/e97d4b18-9a8c-4547-9e2a-42cfddaf83c6)

**Comment by JurreSerrarens** [comment]
Gutterman ULTRAKILL???!??!!?

![Gutterman](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpreview.redd.it%2Fgutterman-concept-art-by-jericho-rus-v0-f9fl5kwhl51c1.jpg%3Fauto%3Dwebp%26s%3D644c51e3a1751b929c81664ade0a2828edeca125&f=1&nofb=1&ipt=d63355dd723b5df609ae811be718e1b9aadd29aed0146509eddca2fe00b14eb0&ipo=images)

**Comment by JurreSerrarens** [comment]
DUde eleden eRearniongg

**Comment by samromer** [comment]
Dung eater ULTRAKIll

**Comment by samromer** [comment]
Gutterman eleden eRearniongg
