### ISSUE TITLE
Create Blazor App

### ISSUE THREAD

**Issue by JurreSerrarens** [JurreSerrarens/C-CovadisDing#8]
## Add a blazor application to the repo

Add a blazor application to the repo next to the other projects

**Comment by samromer** [comment]
![GreatWar](https://github.com/JurreSerrarens/C-CovadisDing/assets/131258016/ef1a8c7e-c6f5-43d2-bf84-e9e584f8cb02)

**Comment by JurreSerrarens** [comment]
![laughing-cat](https://github.com/JurreSerrarens/C-CovadisDing/assets/131258264/bf625c98-5bf2-40ca-84b5-4dd9312a013a)

**Comment by samromer** [comment]
![aClown](https://github.com/JurreSerrarens/C-CovadisDing/assets/131258016/90a4f12b-3b99-453a-b42a-b0309875a154)
